/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSystemRouteRouteImport } from './routes/_authenticated/system/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedMonitorRouteRouteImport } from './routes/_authenticated/monitor/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedSystemLogsRouteRouteImport } from './routes/_authenticated/system/logs/route'
import { Route as AuthenticatedSystemUsersIndexRouteImport } from './routes/_authenticated/system/users/index'
import { Route as AuthenticatedSystemRolesIndexRouteImport } from './routes/_authenticated/system/roles/index'
import { Route as AuthenticatedSystemMenusIndexRouteImport } from './routes/_authenticated/system/menus/index'
import { Route as AuthenticatedSystemDeptsIndexRouteImport } from './routes/_authenticated/system/depts/index'
import { Route as AuthenticatedMonitorServerIndexRouteImport } from './routes/_authenticated/monitor/server/index'
import { Route as AuthenticatedMonitorOnlineIndexRouteImport } from './routes/_authenticated/monitor/online/index'
import { Route as AuthenticatedMonitorJobsIndexRouteImport } from './routes/_authenticated/monitor/jobs/index'
import { Route as AuthenticatedMonitorCacheIndexRouteImport } from './routes/_authenticated/monitor/cache/index'
import { Route as AuthenticatedMonitorCacheListIndexRouteImport } from './routes/_authenticated/monitor/cache-list/index'
import { Route as AuthenticatedComponentsTreeIndexRouteImport } from './routes/_authenticated/components/tree/index'
import { Route as AuthenticatedSystemLogsOperationIndexRouteImport } from './routes/_authenticated/system/logs/operation/index'
import { Route as AuthenticatedSystemLogsLoginIndexRouteImport } from './routes/_authenticated/system/logs/login/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSystemRouteRoute =
  AuthenticatedSystemRouteRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorRouteRoute =
  AuthenticatedMonitorRouteRouteImport.update({
    id: '/monitor',
    path: '/monitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemLogsRouteRoute =
  AuthenticatedSystemLogsRouteRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedSystemRouteRoute,
  } as any)
const AuthenticatedSystemUsersIndexRoute =
  AuthenticatedSystemUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedSystemRouteRoute,
  } as any)
const AuthenticatedSystemRolesIndexRoute =
  AuthenticatedSystemRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedSystemRouteRoute,
  } as any)
const AuthenticatedSystemMenusIndexRoute =
  AuthenticatedSystemMenusIndexRouteImport.update({
    id: '/menus/',
    path: '/menus/',
    getParentRoute: () => AuthenticatedSystemRouteRoute,
  } as any)
const AuthenticatedSystemDeptsIndexRoute =
  AuthenticatedSystemDeptsIndexRouteImport.update({
    id: '/depts/',
    path: '/depts/',
    getParentRoute: () => AuthenticatedSystemRouteRoute,
  } as any)
const AuthenticatedMonitorServerIndexRoute =
  AuthenticatedMonitorServerIndexRouteImport.update({
    id: '/server/',
    path: '/server/',
    getParentRoute: () => AuthenticatedMonitorRouteRoute,
  } as any)
const AuthenticatedMonitorOnlineIndexRoute =
  AuthenticatedMonitorOnlineIndexRouteImport.update({
    id: '/online/',
    path: '/online/',
    getParentRoute: () => AuthenticatedMonitorRouteRoute,
  } as any)
const AuthenticatedMonitorJobsIndexRoute =
  AuthenticatedMonitorJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedMonitorRouteRoute,
  } as any)
const AuthenticatedMonitorCacheIndexRoute =
  AuthenticatedMonitorCacheIndexRouteImport.update({
    id: '/cache/',
    path: '/cache/',
    getParentRoute: () => AuthenticatedMonitorRouteRoute,
  } as any)
const AuthenticatedMonitorCacheListIndexRoute =
  AuthenticatedMonitorCacheListIndexRouteImport.update({
    id: '/cache-list/',
    path: '/cache-list/',
    getParentRoute: () => AuthenticatedMonitorRouteRoute,
  } as any)
const AuthenticatedComponentsTreeIndexRoute =
  AuthenticatedComponentsTreeIndexRouteImport.update({
    id: '/components/tree/',
    path: '/components/tree/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemLogsOperationIndexRoute =
  AuthenticatedSystemLogsOperationIndexRouteImport.update({
    id: '/operation/',
    path: '/operation/',
    getParentRoute: () => AuthenticatedSystemLogsRouteRoute,
  } as any)
const AuthenticatedSystemLogsLoginIndexRoute =
  AuthenticatedSystemLogsLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => AuthenticatedSystemLogsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/monitor': typeof AuthenticatedMonitorRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/system': typeof AuthenticatedSystemRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/system/logs': typeof AuthenticatedSystemLogsRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/components/tree': typeof AuthenticatedComponentsTreeIndexRoute
  '/monitor/cache-list': typeof AuthenticatedMonitorCacheListIndexRoute
  '/monitor/cache': typeof AuthenticatedMonitorCacheIndexRoute
  '/monitor/jobs': typeof AuthenticatedMonitorJobsIndexRoute
  '/monitor/online': typeof AuthenticatedMonitorOnlineIndexRoute
  '/monitor/server': typeof AuthenticatedMonitorServerIndexRoute
  '/system/depts': typeof AuthenticatedSystemDeptsIndexRoute
  '/system/menus': typeof AuthenticatedSystemMenusIndexRoute
  '/system/roles': typeof AuthenticatedSystemRolesIndexRoute
  '/system/users': typeof AuthenticatedSystemUsersIndexRoute
  '/system/logs/login': typeof AuthenticatedSystemLogsLoginIndexRoute
  '/system/logs/operation': typeof AuthenticatedSystemLogsOperationIndexRoute
}
export interface FileRoutesByTo {
  '/monitor': typeof AuthenticatedMonitorRouteRouteWithChildren
  '/system': typeof AuthenticatedSystemRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/system/logs': typeof AuthenticatedSystemLogsRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/components/tree': typeof AuthenticatedComponentsTreeIndexRoute
  '/monitor/cache-list': typeof AuthenticatedMonitorCacheListIndexRoute
  '/monitor/cache': typeof AuthenticatedMonitorCacheIndexRoute
  '/monitor/jobs': typeof AuthenticatedMonitorJobsIndexRoute
  '/monitor/online': typeof AuthenticatedMonitorOnlineIndexRoute
  '/monitor/server': typeof AuthenticatedMonitorServerIndexRoute
  '/system/depts': typeof AuthenticatedSystemDeptsIndexRoute
  '/system/menus': typeof AuthenticatedSystemMenusIndexRoute
  '/system/roles': typeof AuthenticatedSystemRolesIndexRoute
  '/system/users': typeof AuthenticatedSystemUsersIndexRoute
  '/system/logs/login': typeof AuthenticatedSystemLogsLoginIndexRoute
  '/system/logs/operation': typeof AuthenticatedSystemLogsOperationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/monitor': typeof AuthenticatedMonitorRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/system': typeof AuthenticatedSystemRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/system/logs': typeof AuthenticatedSystemLogsRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/components/tree/': typeof AuthenticatedComponentsTreeIndexRoute
  '/_authenticated/monitor/cache-list/': typeof AuthenticatedMonitorCacheListIndexRoute
  '/_authenticated/monitor/cache/': typeof AuthenticatedMonitorCacheIndexRoute
  '/_authenticated/monitor/jobs/': typeof AuthenticatedMonitorJobsIndexRoute
  '/_authenticated/monitor/online/': typeof AuthenticatedMonitorOnlineIndexRoute
  '/_authenticated/monitor/server/': typeof AuthenticatedMonitorServerIndexRoute
  '/_authenticated/system/depts/': typeof AuthenticatedSystemDeptsIndexRoute
  '/_authenticated/system/menus/': typeof AuthenticatedSystemMenusIndexRoute
  '/_authenticated/system/roles/': typeof AuthenticatedSystemRolesIndexRoute
  '/_authenticated/system/users/': typeof AuthenticatedSystemUsersIndexRoute
  '/_authenticated/system/logs/login/': typeof AuthenticatedSystemLogsLoginIndexRoute
  '/_authenticated/system/logs/operation/': typeof AuthenticatedSystemLogsOperationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/monitor'
    | '/settings'
    | '/system'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/system/logs'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/home'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/components/tree'
    | '/monitor/cache-list'
    | '/monitor/cache'
    | '/monitor/jobs'
    | '/monitor/online'
    | '/monitor/server'
    | '/system/depts'
    | '/system/menus'
    | '/system/roles'
    | '/system/users'
    | '/system/logs/login'
    | '/system/logs/operation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/monitor'
    | '/system'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/system/logs'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/home'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/components/tree'
    | '/monitor/cache-list'
    | '/monitor/cache'
    | '/monitor/jobs'
    | '/monitor/online'
    | '/monitor/server'
    | '/system/depts'
    | '/system/menus'
    | '/system/roles'
    | '/system/users'
    | '/system/logs/login'
    | '/system/logs/operation'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/monitor'
    | '/_authenticated/settings'
    | '/_authenticated/system'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/system/logs'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/home/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/components/tree/'
    | '/_authenticated/monitor/cache-list/'
    | '/_authenticated/monitor/cache/'
    | '/_authenticated/monitor/jobs/'
    | '/_authenticated/monitor/online/'
    | '/_authenticated/monitor/server/'
    | '/_authenticated/system/depts/'
    | '/_authenticated/system/menus/'
    | '/_authenticated/system/roles/'
    | '/_authenticated/system/users/'
    | '/_authenticated/system/logs/login/'
    | '/_authenticated/system/logs/operation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor': {
      id: '/_authenticated/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AuthenticatedMonitorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/logs': {
      id: '/_authenticated/system/logs'
      path: '/logs'
      fullPath: '/system/logs'
      preLoaderRoute: typeof AuthenticatedSystemLogsRouteRouteImport
      parentRoute: typeof AuthenticatedSystemRouteRoute
    }
    '/_authenticated/system/users/': {
      id: '/_authenticated/system/users/'
      path: '/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AuthenticatedSystemUsersIndexRouteImport
      parentRoute: typeof AuthenticatedSystemRouteRoute
    }
    '/_authenticated/system/roles/': {
      id: '/_authenticated/system/roles/'
      path: '/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof AuthenticatedSystemRolesIndexRouteImport
      parentRoute: typeof AuthenticatedSystemRouteRoute
    }
    '/_authenticated/system/menus/': {
      id: '/_authenticated/system/menus/'
      path: '/menus'
      fullPath: '/system/menus'
      preLoaderRoute: typeof AuthenticatedSystemMenusIndexRouteImport
      parentRoute: typeof AuthenticatedSystemRouteRoute
    }
    '/_authenticated/system/depts/': {
      id: '/_authenticated/system/depts/'
      path: '/depts'
      fullPath: '/system/depts'
      preLoaderRoute: typeof AuthenticatedSystemDeptsIndexRouteImport
      parentRoute: typeof AuthenticatedSystemRouteRoute
    }
    '/_authenticated/monitor/server/': {
      id: '/_authenticated/monitor/server/'
      path: '/server'
      fullPath: '/monitor/server'
      preLoaderRoute: typeof AuthenticatedMonitorServerIndexRouteImport
      parentRoute: typeof AuthenticatedMonitorRouteRoute
    }
    '/_authenticated/monitor/online/': {
      id: '/_authenticated/monitor/online/'
      path: '/online'
      fullPath: '/monitor/online'
      preLoaderRoute: typeof AuthenticatedMonitorOnlineIndexRouteImport
      parentRoute: typeof AuthenticatedMonitorRouteRoute
    }
    '/_authenticated/monitor/jobs/': {
      id: '/_authenticated/monitor/jobs/'
      path: '/jobs'
      fullPath: '/monitor/jobs'
      preLoaderRoute: typeof AuthenticatedMonitorJobsIndexRouteImport
      parentRoute: typeof AuthenticatedMonitorRouteRoute
    }
    '/_authenticated/monitor/cache/': {
      id: '/_authenticated/monitor/cache/'
      path: '/cache'
      fullPath: '/monitor/cache'
      preLoaderRoute: typeof AuthenticatedMonitorCacheIndexRouteImport
      parentRoute: typeof AuthenticatedMonitorRouteRoute
    }
    '/_authenticated/monitor/cache-list/': {
      id: '/_authenticated/monitor/cache-list/'
      path: '/cache-list'
      fullPath: '/monitor/cache-list'
      preLoaderRoute: typeof AuthenticatedMonitorCacheListIndexRouteImport
      parentRoute: typeof AuthenticatedMonitorRouteRoute
    }
    '/_authenticated/components/tree/': {
      id: '/_authenticated/components/tree/'
      path: '/components/tree'
      fullPath: '/components/tree'
      preLoaderRoute: typeof AuthenticatedComponentsTreeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/logs/operation/': {
      id: '/_authenticated/system/logs/operation/'
      path: '/operation'
      fullPath: '/system/logs/operation'
      preLoaderRoute: typeof AuthenticatedSystemLogsOperationIndexRouteImport
      parentRoute: typeof AuthenticatedSystemLogsRouteRoute
    }
    '/_authenticated/system/logs/login/': {
      id: '/_authenticated/system/logs/login/'
      path: '/login'
      fullPath: '/system/logs/login'
      preLoaderRoute: typeof AuthenticatedSystemLogsLoginIndexRouteImport
      parentRoute: typeof AuthenticatedSystemLogsRouteRoute
    }
  }
}

interface AuthenticatedMonitorRouteRouteChildren {
  AuthenticatedMonitorCacheListIndexRoute: typeof AuthenticatedMonitorCacheListIndexRoute
  AuthenticatedMonitorCacheIndexRoute: typeof AuthenticatedMonitorCacheIndexRoute
  AuthenticatedMonitorJobsIndexRoute: typeof AuthenticatedMonitorJobsIndexRoute
  AuthenticatedMonitorOnlineIndexRoute: typeof AuthenticatedMonitorOnlineIndexRoute
  AuthenticatedMonitorServerIndexRoute: typeof AuthenticatedMonitorServerIndexRoute
}

const AuthenticatedMonitorRouteRouteChildren: AuthenticatedMonitorRouteRouteChildren =
  {
    AuthenticatedMonitorCacheListIndexRoute:
      AuthenticatedMonitorCacheListIndexRoute,
    AuthenticatedMonitorCacheIndexRoute: AuthenticatedMonitorCacheIndexRoute,
    AuthenticatedMonitorJobsIndexRoute: AuthenticatedMonitorJobsIndexRoute,
    AuthenticatedMonitorOnlineIndexRoute: AuthenticatedMonitorOnlineIndexRoute,
    AuthenticatedMonitorServerIndexRoute: AuthenticatedMonitorServerIndexRoute,
  }

const AuthenticatedMonitorRouteRouteWithChildren =
  AuthenticatedMonitorRouteRoute._addFileChildren(
    AuthenticatedMonitorRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedSystemLogsRouteRouteChildren {
  AuthenticatedSystemLogsLoginIndexRoute: typeof AuthenticatedSystemLogsLoginIndexRoute
  AuthenticatedSystemLogsOperationIndexRoute: typeof AuthenticatedSystemLogsOperationIndexRoute
}

const AuthenticatedSystemLogsRouteRouteChildren: AuthenticatedSystemLogsRouteRouteChildren =
  {
    AuthenticatedSystemLogsLoginIndexRoute:
      AuthenticatedSystemLogsLoginIndexRoute,
    AuthenticatedSystemLogsOperationIndexRoute:
      AuthenticatedSystemLogsOperationIndexRoute,
  }

const AuthenticatedSystemLogsRouteRouteWithChildren =
  AuthenticatedSystemLogsRouteRoute._addFileChildren(
    AuthenticatedSystemLogsRouteRouteChildren,
  )

interface AuthenticatedSystemRouteRouteChildren {
  AuthenticatedSystemLogsRouteRoute: typeof AuthenticatedSystemLogsRouteRouteWithChildren
  AuthenticatedSystemDeptsIndexRoute: typeof AuthenticatedSystemDeptsIndexRoute
  AuthenticatedSystemMenusIndexRoute: typeof AuthenticatedSystemMenusIndexRoute
  AuthenticatedSystemRolesIndexRoute: typeof AuthenticatedSystemRolesIndexRoute
  AuthenticatedSystemUsersIndexRoute: typeof AuthenticatedSystemUsersIndexRoute
}

const AuthenticatedSystemRouteRouteChildren: AuthenticatedSystemRouteRouteChildren =
  {
    AuthenticatedSystemLogsRouteRoute:
      AuthenticatedSystemLogsRouteRouteWithChildren,
    AuthenticatedSystemDeptsIndexRoute: AuthenticatedSystemDeptsIndexRoute,
    AuthenticatedSystemMenusIndexRoute: AuthenticatedSystemMenusIndexRoute,
    AuthenticatedSystemRolesIndexRoute: AuthenticatedSystemRolesIndexRoute,
    AuthenticatedSystemUsersIndexRoute: AuthenticatedSystemUsersIndexRoute,
  }

const AuthenticatedSystemRouteRouteWithChildren =
  AuthenticatedSystemRouteRoute._addFileChildren(
    AuthenticatedSystemRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMonitorRouteRoute: typeof AuthenticatedMonitorRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSystemRouteRoute: typeof AuthenticatedSystemRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedComponentsTreeIndexRoute: typeof AuthenticatedComponentsTreeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMonitorRouteRoute: AuthenticatedMonitorRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSystemRouteRoute: AuthenticatedSystemRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedComponentsTreeIndexRoute: AuthenticatedComponentsTreeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
